### ISSUE TITLE
Inquiry About Methylation Data for ONT

### ISSUE THREAD

**Issue by zaka-edd** [Platinum-Pedigree-Consortium/Platinum-Pedigree-Datasets#1]
Hi there,

I’m currently working with ONT long-read sequencing data, and I’m curious about the methylation data. Is there any chance this data will be supported or published in this repository?

If you have any recommendations on who I could contact about this data that would be appreciated.

Thank you in advance :)

**Comment by zeeev** [comment]
Hi @zaka-edd,

Thanks for your interest. I'll check with the group and get back with you by next week.

Best wishes,

Zev

**Comment by zaka-edd** [comment]
Hi @zeeev,

I was wondering if you have an update :)

Best wishes,
Zak

**Comment by zaka-edd** [comment]
Hi @zeeev,

I was wondering if you have an update :)

Kind regards,
Zak
